### ISSUE TITLE
Question regarding coord system and ego correction

### ISSUE THREAD

**Issue by richardkxu** [itailang/SCOOP#1]
Hi, thank you for opensource the repo! I have a few questions regarding coord system and ego correction. I have done a visualization (attached below) for the provided kitti_v dataset. The dataset seems to have nonzero GT flow for almost all points (including some static points like walls). 

1. Which coordinate system do you use for the kitti dataset? 
2. Is there a design choice reason not applying the ego motion correction before sending to train scoop?
3. Which ground removal algorithm are you using? What other preprocessing have you applied?

Thank you so much!

![kitti-batch2](https://user-images.githubusercontent.com/25449141/216396280-0a5bdece-6d8b-4b32-99e9-cc98b616245b.png)

**Comment by itailang** [comment]
Dear @richardkxu,

I appreciate your interest in our work!

Regarding your questions:
1. The dataset contains holistic scene motion that includes the ego sensor motion and the objects' motion. Thus, static points has non-zero ground-truth flow.
2. As such, we decided doing a holistic motion estimation method.
3. We use the same data and pre-processing as in [FLOT](https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123730528.pdf).

Feel free to ask further questions if any.

**Comment by richardkxu** [comment]
Thanks for the prompt reply!
