### ISSUE TITLE
Learning curve and hypyerparameter tuning on sparse data

### ISSUE THREAD

**Issue by richardkxu** [itailang/SCOOP#2]
Hi, thanks for the great work! I have a few questions regarding the hyperparameter tuning:

1. why the `train_corr_conf_loss` and `val_corr_conf_loss` increases while all other three losses decreases overtime when training with default setting on kitti_v? Is this expected? Can you provide the learning curve on your side as a reference?
2. I try to adapt scoop for nuscenes dataset. The learning curve seems to converge much slower and have much higher absolute loss values than kitti. The nuscenes dataset is more sparse and has many static points with zero GT flow. Do you have any suggestions for adjusting `--nb_neigh_smooth_flow`, `--nb_neigh_cross_recon` or any other hyperparameters accordingly? should `--nb_neigh_cross_recon` always be double the value of `--nb_neigh_smooth_flow`?

![image](https://user-images.githubusercontent.com/25449141/216398847-b415bb18-2fbc-4896-a0a5-bef5f5e7dcaf.png)

**Comment by itailang** [comment]
Dear @richardkxu,

Thank you for our interest in our work!

Here are my answers:
1. The correspondence confidence loss is meant to counteract the trivial solution of zero confidence for all the points. However, while the network learns the point feature representation and the other losses decrease, this loss can increase a bit. Note that the confidence loss is increased from about 0.1 to about 0.2. It means that the average point confidence decreases from about 0.9 to about 0.8, showing that we are far from the trivial zero confidence solution. Bottom line, the training behavior you observe is fine.
2. Both these parameters influence the smoothness of the resulting flow field. If the estimated scene flow that you get is too smooth, decrease the values of these parameters, and vice versa. The parameters can be set independently. One does not necessarily have to be double than the other. Note that you may also adapt the weight $\alpha_{flow}$, which controls the influence level of the smoothness loss. 

Feel free to share further questions if you have.

**Comment by richardkxu** [comment]
Got it! Thank you for the prompt reply!
