### ISSUE TITLE
Evaluation Concern

### ISSUE THREAD

**Issue by rahuja123** [itailang/SCOOP#3]
In your evaluation file, you divide the point cloud into chunks of 2048 points of say batch b. Then you estimate flow for all these batches independently and concatenate the flow results. The full pointcloud is evaluated right? Not just any randomly sampled 2048 points? 

Please do correct me, if I am wrong?

**Comment by itailang** [comment]
Dear @rahuja123,

Thank you for your interest in the project. Yes, the full point cloud is evaluated.

**Comment by rahuja123** [comment]
You compare different models which were evaluated using either 2048 points or 8192 points. If we consider all the points for evaluation, won't our results be better by default? If we don't take chunks and just input a 2048 random sampled pointcloud pair, will the results be same?
Please do correct me, if I am wrong?

**Comment by itailang** [comment]
Dear @rahuja123,

Please see my answer to issue #4.
