### ISSUE TITLE
Evaluation Concern Part 2

### ISSUE THREAD

**Issue by rahuja123** [itailang/SCOOP#4]
Continuing #3 issue,

You compare different models which were evaluated using either 2048 points or 8192 points.
Whereas your model does evaluation on whole pointcloud but run inference on chunks of 2048 points. 

If we consider all the points for evaluation, won't our results be better by default? If we don't take chunks and just input a 2048 random sampled pointcloud pair, will the results be same as reported?

**Comment by itailang** [comment]
Dear @rahuja123,

Thank you for your comment. We do evaluate on 8192 points. I will add evaluation on 2048 points as well and let you know.

**Comment by itailang** [comment]
Dear @rahuja123,

You may find the evaluation commands for 2048 point in the [readme](https://github.com/itailang/SCOOP/blob/master/README.md) file.

**Comment by rahuja123** [comment]
Hi, 
thanks @itailang  for this. 

I had another doubt. As you had mentioned in the paper that your results for NSFP and Graph Prior are a bit different to what they reported. So are these results reproduced for the whole pointcloud? Or 8192 points? And are these reproduced by you or are they taken from the paper. 

Thank you :D

**Comment by itailang** [comment]
Dear @rahuja123,

The results are for the whole point cloud. They are reproduced by me for the evaluation setting I used as in previous learning-based papers (points with depth up to 35 meters).

Let me know if you have any further questions!

**Comment by rahuja123** [comment]
Thank you @itailang 

This was helpful :D
