### ISSUE TITLE
Test samples idxs differ from  Rigid3DSceneFlow

### ISSUE THREAD

**Issue by yanconglin** [itailang/SCOOP#5]
Hi, thank you for releasing the code.
I find the stereo-kitti test samples indices differ from the Rigid3DSceneFlow [stereo-kitti](https://github.com/zgojcic/Rigid3DSceneFlow/blob/master/configs/datasets/stereo_kitti/test.txt) and [lidar-kitti](https://github.com/zgojcic/Rigid3DSceneFlow/blob/master/configs/datasets/lidar_kitti/test.txt). Could you please elaborate? Also, could you please confirm which kitti dataset is adopted in the evaluation, stereo-kitti or lidar-kitti? I find it hard to distinguish these two.
Thank you!

**Comment by itailang** [comment]
Dear @yanconglin,

Thank you for your interest in our work.

The stereo-kitti dataset was adopted. I used the [HPLFlowNet version of the dataset](https://github.com/laoreja/HPLFlowNet/blob/master/datasets/kitti.py) for evaluation.
